### ISSUE TITLE
Missing device after Crossfire 2.07 update

### ISSUE THREAD

**Issue by umbertoghio** [codecae/betaflight-tx-lua-revised#10]
Hi there, 
me bothering again :-)

Today I have upgraded my crossfire micro tx to firmware 2.07, then proceeded in binding my two drones and pushing the blue button for upgrading the receiver over the air.

Once done the Betaflight 3.2.0:BFF3 item no longer shows up, even after 1 minute wait  (Micro TX and Micro RX are there)

**Comment by codecae** [comment]
I have informed TBS about this issue.  Roll back to 2.06 for now.

**Comment by codecae** [comment]
2.07 addresses a bug in the X7, so the upgrade really isn't necessary if you're using a X9

**Comment by umbertoghio** [comment]
Hi, thanks for the follow up, I was unsure if worth updating, but I tried when I seen "other bug fixes".
This is probably something only TBS can fix, will wait for 2.08 then 👍
