### ISSUE TITLE
Don't need separate scripts for CRSF/SmartPort

### ISSUE THREAD

**Issue by apocolipse** [codecae/betaflight-tx-lua-revised#11]
I noticed you have a separate branch dedicated to CRSF.  This isn't needed.  Just use some logic to check for either `RSSI` or `1RSS` values not being 0 and you can easily determine which is running, then fork to some separate methods for processing data.

```lua
local mode = 0  -- no device available
if not (getValue("RSSI") == 0) then
  mode = 1  -- smartport
elseif not (getValue("1RSS") == 0) then
  mode = 2  -- crossfire
else
  mode = 0  
end
```

**Comment by codecae** [comment]
The telemetry push functions in opentx are different, as are the buffer sizes.  The branches are very similar in ways but they are different for a important reasons.

**Comment by apocolipse** [comment]
Its better to have conditional and just keep all the same constants in the same script, that way the differences are self documenting and not disparate.  It also makes it more difficult for typical end users.  Just trying to help.

**Comment by codecae** [comment]
Understand and appreciate the feedback.  I have attempted to unify the scripts as much as possible.  The controller layer and underlying templates are identical, but the model layers are different to save on memory use.  It barely fits into memory as it sits now, so adding more constants and logic will only eat up precious overhead.  Eventually they will be unified in a single master branch, with the differences separated out more distinctly.  For now, though (until stable) I pan on maintaining them mostly separate until the common areas can be more unified.

**Comment by apocolipse** [comment]
You could abstract CRSF and SmartPort to separate transport layers and import whichever is needed accordingly at runtime.

**Comment by codecae** [comment]
that's pretty much what it's doing now.  The only differences are found in the msp_sp and msp_crsf scripts (for the most part).

**Comment by codecae** [comment]
Btw I realized now that I clicked close when I meant to click comment :)  That probably looked like a total dick move.  My bad.

**Comment by apocolipse** [comment]
Cool sounds like you're on the right path :)  The initial separate branches just rubbed my programmer sensibilities the wrong way :D 
Thanks for re-opening, let me know if you need some help or feedback (I've not done much LUA on taranis but used to tear it up with WoW addons :D )

**Comment by codecae** [comment]
I have full intention of merging them.  Just for now, I'm ironing out where all of the common elements reside.  Once they are more uniform, they'll be merged together.

**Comment by codecae** [comment]
Done deal :)

**Comment by apocolipse** [comment]
Nice, very elegant.  Like your approach 👌

**Comment by codecae** [comment]
Managed to dry it out pretty well.
