### ISSUE TITLE
Inversion is not "motor direction is reversed"

### ISSUE THREAD

**Issue by mickkn** [codecae/betaflight-tx-lua-revised#2]
Inversion does not point to the correct variable for inverted motors, if that is what it's for :) 

It says OFF in Lua script but is enabled in GUI.

**Comment by codecae** [comment]
Not to be confused with yaw direction ! :)   I'll be removing this, as it's a bit misleading.

**Comment by codecae** [comment]
It's properly setting the value of motor_pwm_inversion, but that is not the same thing as yaw_motors_reversed.  I will likely be removing this due to confusion.

**Comment by codecae** [comment]
This item has been removed from the menu to curb confusion.  It has little to no value in an in-field context.
