### ISSUE TITLE
PID's (and all other values) not saving 

### ISSUE THREAD

**Issue by VoicOfReason** [codecae/betaflight-tx-lua-revised#21]
I have a Omnibus F7 V2, and am using latest version of Taranis and TBS Crossfire Micro V2 with 2.08 beta firmware. Voltage telemetry is sent back to Taranis (if you're interested). Also, I can read all PID, rate, Tx settings as well (using Tramp VTx). However, when I hit MENU and go to SAVE, it reverts back to previous values. I've tried multiple times, and even tried a stick command to save values, but no success. Betaflight is 3.2RC5... I downgraded TBS to 2.06 official and VTX settings WILL save, but PID's, rates, etc. and all other settings still will NOT save.

**Comment by codecae** [comment]
This is a known issue that is being addressed in betaflight.  Hoping to have the fix in soon, just waiting on an approval.  I understand this is inconvenient, but rest assured that the fix has been built and will be soon be publically available.

**Comment by VoicOfReason** [comment]
Someone said there was a workaround. Do you know of one for now?

**Comment by codecae** [comment]
I do :)  I have been trying to reach out to you on facebook.

**Comment by VoicOfReason** [comment]
Oh! That was you! I don't see the PM yet. :)
On 9/29/2017 6:30:40 PM, codecae <notifications@github.com> wrote:
I do :) I have been trying to reach out to you on facebook.

**Comment by codecae** [comment]
It shows that you are offline

**Comment by VoicOfReason** [comment]
That's weird. I'm right on the Facebook page.

On 9/29/2017 6:32:21 PM, codecae <notifications@github.com> wrote:
It shows that you are offline

**Comment by VoicOfReason** [comment]
I guess you can just email me here.
On 9/29/2017 6:32:45 PM, Peter Freund <wpfreund@gmail.com> wrote:
That's weird. I'm right on the Facebook page.

On 9/29/2017 6:32:21 PM, codecae <notifications@github.com> wrote:
It shows that you are offline

**Comment by codecae** [comment]
Trying to share files with you, which I can't do on a facebook post.  I'll share it here instead.

**Comment by codecae** [comment]
Try this firmware and see if it helps.

[betaflight_3.2.0_OMNIBUSF7V2.hex.zip](https://github.com/codecae/betaflight-tx-lua-revised/files/1345908/betaflight_3.2.0_OMNIBUSF7V2.hex.zip)

**Comment by VoicOfReason** [comment]
Thanks!
On 9/29/2017 6:35:02 PM, codecae <notifications@github.com> wrote:
Try this firmware and see if it helps.
betaflight_3.2.0_OMNIBUSF7V2.hex.zip [https://github.com/codecae/betaflight-tx-lua-revised/files/1345908/betaflight_3.2.0_OMNIBUSF7V2.hex.zip]

**Comment by Tubemaster** [comment]
It would be great to get a hex for the Matek f405 osd board that allows saving of the PIDs.
Many thanks

**Comment by codecae** [comment]
When I get home, I will create a zip of every target and post it for download... Stay tuned

**Comment by VoicOfReason** [comment]
Awesome! How long until this fix is incorporated in latest Betaflight build?
On 9/30/2017 9:18:05 AM, codecae <notifications@github.com> wrote:
When I get home, I will create a zip of every target and post it for download... Stay tuned

**Comment by Tubemaster** [comment]
legend!

**Comment by VoicOfReason** [comment]
Is the Firmware going to be similar enough to RC5 that I can just do a DUMP of my current config?
On 9/30/2017 9:18:05 AM, codecae <notifications@github.com> wrote:
When I get home, I will create a zip of every target and post it for download... Stay tuned

**Comment by codecae** [comment]
The merge is only pending one approval.  The work is done.  Once the reviewer signs off, it will be merged soon after.  Shouldn't be much longer.  I think the delay is due to time zone differences.

**Comment by codecae** [comment]
Just perform a diff in the clinic and copy it.  Flash, paste, and save.

**Comment by VoicOfReason** [comment]
So, do the DIFF first, and then flash new firmware, paste diff values, and
save?

**Comment by codecae** [comment]
Yes

**Comment by codecae** [comment]
@Tubemaster 

[betaflight_3.2.0_MATEKF405.hex.zip](https://github.com/codecae/betaflight-tx-lua-revised/files/1346739/betaflight_3.2.0_MATEKF405.hex.zip)

**Comment by VoicOfReason** [comment]
Is this all of the models zipped together?

-- 
Peter Freund
Sent with Airmail

**Comment by codecae** [comment]
no.. taking this case by case

**Comment by VoicOfReason** [comment]
Oh ok. I guess I also Need omnibus f4sd and regular omnibus f4, if
possible. Thanks.

-- 
Peter Freund
Sent with Airmail

**Comment by codecae** [comment]
@VoicOfReason 
[betaflight_3.2.0_OMNIBUSF4_F4SD.zip](https://github.com/codecae/betaflight-tx-lua-revised/files/1346747/betaflight_3.2.0_OMNIBUSF4_F4SD.zip)

**Comment by arrowcircle** [comment]
dys f4 pro?

**Comment by codecae** [comment]
PLEASE NOTE -- THIS FIRMWARE IS ONE-OFF AND WILL NOT BE SUPPORTED BY THE BETAFLIGHT TEAM UNTIL IT HAS BEEN OFFICIALLY MERGED. IF YOU RUN INTO ISSUES, PLEASE CONTACT ME DIRECTLY AND DO NOT OPEN AN ISSUE ON THE BETAFLIGHT ISSUES LIST!

@arrowcircle
[betaflight_3.2.0_DYSF4PRO.hex.zip](https://github.com/codecae/betaflight-tx-lua-revised/files/1346755/betaflight_3.2.0_DYSF4PRO.hex.zip)

**Comment by VoicOfReason** [comment]
Got it. I’m sorry to ask this but are you very familiar with flight
controllers in order to answer a question I have?

-- 
Peter Freund
Sent with Airmail

**Comment by codecae** [comment]
@VoicOfReason possibly. no promises, though :)

**Comment by carloscampos775** [comment]
Hi could you please post a Betaflight F3 fix

**Comment by codecae** [comment]
PLEASE NOTE -- THIS FIRMWARE IS ONE-OFF AND WILL NOT BE SUPPORTED BY THE BETAFLIGHT TEAM UNTIL IT HAS BEEN OFFICIALLY MERGED. IF YOU RUN INTO ISSUES, PLEASE CONTACT ME DIRECTLY AND DO NOT OPEN AN ISSUE ON THE BETAFLIGHT ISSUES LIST!

@carloscampos775 
[betaflight_3.2.0_BETAFLIGHTF3.hex.zip](https://github.com/codecae/betaflight-tx-lua-revised/files/1347131/betaflight_3.2.0_BETAFLIGHTF3.hex.zip)

**Comment by VoicOfReason** [comment]
Jose just joined this email thread. He needs the updated firmware for CL
Racing flight controller to save PID's. Thanks.

**Comment by codecae** [comment]
@VoicOfReason  which one

**Comment by VoicOfReason** [comment]
I included him in this email so he should respond...

**Comment by codecae** [comment]
he'd be better served by coming onto github directly.  I don't think an email will come into the thread if he doesn't have a github account

**Comment by VoicOfReason** [comment]
Now that RC6 is out, could I get RC6 version that works with PID's for
these FC's:

Omnibus F7V2
Betaflight F3
Omnibus F4
Omnibus F4SD

**Comment by codecae** [comment]
There is nothing significant in rc6 vs what you were given.  I kept it very
current  with all changes.  It is very likely that the change will be
merged soon, anyway.

**Comment by VoicOfReason** [comment]
OK. Sounds good. Btw, I'm having accelerometer problems with RC5 and RC6.
Not sure how many people this affects, but:

https://github.com/betaflight/betaflight/issues/4268

**Comment by codecae** [comment]
I was just reviewing the issues list and saw this.

**Comment by codecae** [comment]
I have posted an archive that contains all targets that should enable saves until Betaflight merges the change into the mainline code.

*PLEASE KEEP IN MIND THAT THIS FIRMWARE IS A ONE-OFF INTERIM UPDATE THAT IS NOT YET PART OF THE SUPPORTED BETAFLIGHT CODEBASE.  IF YOU HAVE ISSUES, PLEASE RETURN HERE TO RAISE THEM OR OPEN THEM IN MY FORK OF THE BETAFLIGHT REPO AND NOT THE BETAFLIGHT REPO!*

[Click here to download the ZIP of all targets](http://bit.ly/2xYtGnE)

**Comment by codecae** [comment]
This issue has been corrected and is now available in the master branch of Betaflight build 242 and greater.  It will be released in stable release 3.2.1 but can be downloaded now from the build repository.

[Click here to visit the available builds for Betaflight](https://ci.betaflight.tech/view/all/builds)
