### ISSUE TITLE
Script syntax error while loading

### ISSUE THREAD

**Issue by djakette123** [codecae/betaflight-tx-lua-revised#24]
Opentx 2.2
Script version 1.0-rc2
BF build #244 (with crossfire telemetry fixed)
Crossfire fw 2.11

error is : attempt to index field 'protocol' (a nil value)

Weird because i was able to load it the first time.

**Comment by codecae** [comment]
Not sure how the protocol could become undefined.  Try recopying the scripts to the card.

**Comment by djakette123** [comment]
Ok it was something with .luac script, had to delete old one manually to make it work.
Problem solve thanks.
