### ISSUE TITLE
[No Telemetry] can't get this script working

### ISSUE THREAD

**Issue by marcosantomo** [codecae/betaflight-tx-lua-revised#28]
I'm testing the script with a X4RSB and a XSR, both with a full working telemetry with my taranis, but asap I launch this script I get "No telemetry". XSR is on the latest firmware.

**Comment by codecae** [comment]
I have repeated your case and have rolled back a recent change that may responsible for this issue.  Please try re-downloading the scripts from the master branch and try again.

**Comment by marcosantomo** [comment]
Ok, now it works on both the receivers! You're doing a really good job, this script is very useful!
