### ISSUE TITLE
scroll wheel not working within updated x7_test script

### ISSUE THREAD

**Issue by josh-kenny** [codecae/betaflight-tx-lua-revised#35]
Telemetry is working perfectly on X7. New script is allowing pid and VTX control enabled within my screens. Upon trying to re execute the Lua script to modify my RX settings the scroll wheel is no longer functioning. Video reference attached.

https://youtu.be/gFWNj-Jx5lE

**Comment by codecae** [comment]
try this one

https://github.com/codecae/betaflight-tx-lua-revised/tree/Preston_x7_test

**Comment by josh-kenny** [comment]
works!
