### ISSUE TITLE
Script syntax erro

### ISSUE THREAD

**Issue by chaserpm** [codecae/betaflight-tx-lua-revised#4]
getting the following error when trying to save after change(s) to setting(s).

Script syntax error
BFui_sp.lua:96
bad argument #1 to 'band' (number expected,
any idea how to fix?

**Comment by codecae** [comment]
can you clarify what it was that you were saving?  what screen were you on?  what changes did you save?

**Comment by chaserpm** [comment]
Changed Dterm Setpoint transition (screen Rates 2/2) from 50 to 40. Tried to save but got the error. Changes were not waved.

**Comment by codecae** [comment]
Thanks, I will try to reproduce and update!

**Comment by codecae** [comment]
I tried several different scenarios to reproduce this issue and could not.  Can you attempt downloading the newest version and see if it works as expected?

**Comment by chaserpm** [comment]
downloaded it again and tried but same issue.  Changes in all the screens except Rates 2/2 works and can be saved but if I change Dterm Setpoint weight or transition it gives me the syntax error.

**Comment by spacebubi** [comment]
not working NOTHING, i've updated my 9XD to all last fmw for that...nothing..i put your files in SD card like other .lua, than when i run it on screen appear "syntax error on line 7"

**Comment by codecae** [comment]
Spacebubi can you please open a separate issue for this?  Please detail how you installed the files on the card so i can better understand what might have happened.

**Comment by codecae** [comment]
@chaserpm I will be updating the script again soon.  It will be a fairly significant overhaul on the menuing system, which should fix your issue.  Sorry for any delay, as I'm trying to fit these fixes in between work and hurricane fallout!

**Comment by codecae** [comment]
can you zip up your SCRIPTS folder and attach it to the issue?  just drag/drop it onto a comment.

**Comment by codecae** [comment]
been nearly 2 weeks and no response.  Closing this issue.
