### ISSUE TITLE
telemetry screen does not work with FRSKY telemetry

### ISSUE THREAD

**Issue by maciek01** [codecae/betaflight-tx-lua-revised#46]
betaflight 3.2
frsky XSR
X9D+
OTX 2.2

telemetry screen woks great with crsf but when i switch to internal tx module and connect to an frsky-xsr based quad i get 'no telemetry' message on the telemetry screen.

i  switched from the default BF.LUA where i had no issues with xsr.

**Comment by codecae** [comment]
If you changed a model from CRSF to FrSky, please rediscover sensors in opentx.

**Comment by codecae** [comment]
I have personally tested this with frsky and do not experience the issue as you describe it.

**Comment by maciek01** [comment]
my bad. i rebooted everything and all works great now with XSR. closing..
